import jsPDF from 'jspdf';
import { format } from 'date-fns';

/**
 * Generate and download a PDF itinerary for the given trip.
 *
 * @param {Object} trip - The full trip object with trip_days and itinerary_items
 */
export async function generatePDF(trip) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  // ── Colors ─────────────────────────────────────────────────────────────
  const TEAL = [20, 184, 166];
  const INK = [15, 23, 42];
  const INK_MUTED = [71, 85, 105];
  const SURFACE = [241, 245, 249];
  const AMBER = [245, 158, 11];
  const VIOLET = [139, 92, 246];

  // ── Cover Page ─────────────────────────────────────────────────────────
  // Header bar
  doc.setFillColor(...TEAL);
  doc.rect(0, 0, pageWidth, 60, 'F');

  // Logo / app name
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('✈ TripNode', margin, 20);

  // Trip title
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text(trip.title || 'My Trip', margin, 40);

  // Meta info
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const metaY = 70;
  doc.setTextColor(...INK);
  doc.text(`📍 ${trip.destination_city}${trip.destination_country ? ', ' + trip.destination_country : ''}`, margin, metaY);
  doc.text(
    `📅 ${format(new Date(trip.start_date), 'MMM d, yyyy')} – ${format(new Date(trip.end_date), 'MMM d, yyyy')}`,
    margin, metaY + 8
  );
  doc.text(`👥 ${trip.traveler_count} traveler${trip.traveler_count !== 1 ? 's' : ''}  ·  🌴 ${trip.travel_style}`, margin, metaY + 16);
  doc.text(`🏨 ${trip.hotel_name}`, margin, metaY + 24);

  // Divider
  doc.setDrawColor(...TEAL);
  doc.setLineWidth(0.5);
  doc.line(margin, metaY + 32, pageWidth - margin, metaY + 32);

  // ── Day Sections ───────────────────────────────────────────────────────
  const days = trip.trip_days || [];
  let yPos = metaY + 44;

  for (const day of days) {
    const items = day.itinerary_items || [];

    // Check if we need a new page
    if (yPos > 240) {
      doc.addPage();
      yPos = 20;
    }

    // Day header
    doc.setFillColor(...SURFACE);
    doc.roundedRect(margin, yPos, contentWidth, 10, 2, 2, 'F');
    doc.setTextColor(...TEAL);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(
      `Day ${day.day_number}${day.date ? '  ·  ' + format(new Date(day.date), 'EEEE, MMMM d') : ''}`,
      margin + 4, yPos + 7
    );
    yPos += 14;

    for (const item of items) {
      if (yPos > 260) {
        doc.addPage();
        yPos = 20;
      }

      // Item status color
      const statusColor = item.type === 'hotel' ? VIOLET : item.status === 'locked' ? AMBER : TEAL;

      // Left status bar
      doc.setFillColor(...statusColor);
      doc.rect(margin, yPos, 3, 20, 'F');

      // Item box
      doc.setFillColor(255, 255, 255);
      doc.roundedRect(margin + 3, yPos, contentWidth - 3, 20, 2, 2, 'F');
      doc.setDrawColor(220, 230, 240);
      doc.setLineWidth(0.3);
      doc.roundedRect(margin + 3, yPos, contentWidth - 3, 20, 2, 2, 'S');

      // Name
      doc.setTextColor(...INK);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.text(item.name.substring(0, 50), margin + 8, yPos + 6);

      // Time + distance
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(...INK_MUTED);
      const timeTxt = item.start_time ? `${item.start_time}${item.end_time ? '–' + item.end_time : ''}` : '';
      const distTxt = item.distance_from_prev_km > 0 ? `  ·  ${item.distance_from_prev_km} km` : '';
      doc.text(timeTxt + distTxt, margin + 8, yPos + 13);

      // Address
      if (item.address) {
        const shortAddr = item.address.split(',').slice(0, 2).join(',').trim().substring(0, 55);
        doc.text('📍 ' + shortAddr, margin + 8, yPos + 19);
      }

      yPos += 23;
    }

    yPos += 6; // Gap between days
  }

  // Footer on last page
  doc.setFontSize(8);
  doc.setTextColor(...INK_MUTED);
  doc.text(
    `Generated by TripNode · ${format(new Date(), 'MMM d, yyyy')}`,
    pageWidth / 2, 290, { align: 'center' }
  );

  // Download
  const filename = `${(trip.title || 'TripNode').replace(/\s+/g, '-').toLowerCase()}-itinerary.pdf`;
  doc.save(filename);
}
